# conda env create -f environment.yml
name: dev-gann
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    # python version
    - python=3.7

    # conda packages
    - numpy=1.19.*
    - pandas=1.1.*
    - gtfparse=1.2.1
    - scanpy=1.6.*

    # pip packages
    - pip
    - pip:
      - -r file:requirements_dev.txt