ARG BASE_CONTAINER=tensorflow/tensorflow:latest-gpu-py3
FROM $BASE_CONTAINER

LABEL authors="Chris Cheshire" \
      description="Docker image for running tensorflow on GPU CAMP"

RUN pip install pandas